name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode Repositori
        uses: actions/checkout@v2

      - name: Siapkan Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Pasang Vercel CLI
        run: npm install --global vercel@latest

      - name: Bangun Artefak Proyek
        run: vercel build

      - name: Deploy Artefak Proyek ke Vercel
        run: vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
